[build.env]
passthrough = [
    "RUST_LOG",
]

[target.aarch64-unknown-linux-gnu]
dockerfile = "./docker/Dockerfile.aarch64"

[target.armv7-unknown-linux-gnueabihf]
dockerfile = "./docker/Dockerfile.armv7"
